services:

  oracle:
    image: gvenzl/oracle-free:latest
    container_name: RORO
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: secret               # Contrase침a del usuario 'oracle'
      APP_USER: REVIEWS              # Usuario que se crear치 autom치ticamente
      APP_USER_PASSWORD: REVIEWS123   # Contrase침a del usuario 'publicaciones'
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - reviews-net

volumes:
  oracle-data:

networks:
  reviews-net:
    driver: bridge