server:
  port: 8082

spring:
  application:
    name: ms-reviews

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##envios
    password: envios123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    propiertes:
      hibernate:
        dialect:  org.hibernate.dialect.Oracle12cDialect